use_frameworks!

platform :ios, '8.0'

target 'WcjCategoryLib_Example' do
  pod 'WcjCategoryLib', :path => '../'

  target 'WcjCategoryLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
