use_frameworks!
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/m13272210634/Specs.git'

target 'WcjCategoryLib_Example' do
#
  pod 'WcjCategoryLib', :path => '../'

  target 'WcjCategoryLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
